title: "Legally Yapping"
subtitle: "Yapping our way through Law School"
name: "By Javeen Matharu & Sarah Rose Mathews"
description: "A blog where we try to explain legal concepts in simple way"

url: "https://legallyyappingcom"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Author profile
author:
  name: "Jas & Sarah"
  avatar: ""
  bio: "Sharing what we have learnt."
  location: "India"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:queries@legallyyapping.com"

# Appearance
minimal_mistakes_skin: "neon"  # try: default, dark, air, contrast

# Navigation
header_pages:
  - index.md
  - about.md

# Footer
footer:
  links:
    - label: "GitHub"
      url: "https://github.com/yourusername"

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true

timezone: Asia/Kolkata
